project:
  type: website
  output-dir: docs

website:
  title: "Complex_Seasonality"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

